"use client";
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Columns3,Orbit,Unlock,LockKeyhole,BookOpen,X,ChevronLeft,ChevronRight,Search,ArrowLeft} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {PassageMap} from '@/components/passage-map';
import {NAMES,refLabel,makeReading,isSourceSection} from '@/lib/gospel';
import type {Index,Group} from '@/lib/gospel';
import {PassageSearchResults} from '@/components/passage-search-results';
import {firstSearchResult,type PassageSearchResult} from '@/lib/passage-search';

type Props={open:boolean;onOpenChange:(v:boolean)=>void;index:Index;books:string[];group:Group;groups:Group[];displayed:Group;preview?:Group;locked:boolean;view:'columns'|'circle';scale:string;onView:(v:'columns'|'circle')=>void;onSelect:(g:Group)=>void;onPreview:(g:Group)=>void;onUnlock:()=>void;onRead:()=>void;onAfterRead:()=>void;query:string;onQuery:(s:string)=>void;searchResult:PassageSearchResult;onSearchSelect:(g:Group)=>void;edition:string;textReady:boolean;textError?:string;onRetryText:()=>void};
export function ExploreMap(p:Props){
 const [searching,setSearching]=useState(false),searchInput=useRef<HTMLInputElement>(null),searchButton=useRef<HTMLButtonElement>(null),dialog=useRef<HTMLDivElement>(null);
 // Flush only the user-initiated opening, keeping focus inside the tap event
 // so iOS can present its keyboard. Closing restores the search trigger.
 const openSearch=()=>{flushSync(()=>setSearching(true));searchInput.current?.focus()};
 const closeSearch=()=>{setSearching(false);searchButton.current?.focus()};
 const choose=(g:Group)=>{p.onSearchSelect(g);searchInput.current?.blur();closeSearch()};
 useEffect(()=>{if(!p.open)setSearching(false)},[p.open]);
 // The visual viewport also shrinks for the iOS keyboard, unlike 100dvh.
 useEffect(()=>{if(!p.open||!searching)return;const viewport=window.visualViewport;if(!viewport)return;const element=dialog.current;const resize=()=>{element?.style.setProperty('--search-viewport-height',viewport.height+'px');element?.style.setProperty('--search-viewport-top',viewport.offsetTop+'px')};resize();viewport.addEventListener('resize',resize);viewport.addEventListener('scroll',resize);return()=>{viewport.removeEventListener('resize',resize);viewport.removeEventListener('scroll',resize);element?.style.removeProperty('--search-viewport-height');element?.style.removeProperty('--search-viewport-top')}},[p.open,searching]);
 const sequence=p.groups.filter(isSourceSection);const step=(n:number)=>{const i=sequence.findIndex(g=>g.id===(p.displayed.parentId||p.displayed.id));if(sequence.length)p.onSelect(sequence[i<0?(n>0?0:sequence.length-1):(i+n+sequence.length)%sequence.length])};
 const readOnClose=useRef(false),returnFocus=useRef<HTMLElement|null>(null);
 // Replace the centered popup utilities at the call site. Production CSS can
 // fold `translate: none` into `transform: none`, leaving individual offsets.
 return <Dialog open={p.open} onOpenChange={p.onOpenChange}><DialogContent ref={dialog} className={'explore-dialog top-0 left-0 translate-x-0 translate-y-0'+(searching?' is-searching':'')} showCloseButton={false} onOpenAutoFocus={e=>{e.preventDefault();returnFocus.current=document.activeElement as HTMLElement;document.querySelector<HTMLButtonElement>('.explore-close')?.focus()}} onCloseAutoFocus={e=>{e.preventDefault();if(readOnClose.current){readOnClose.current=false;requestAnimationFrame(p.onAfterRead)}else returnFocus.current?.focus()}} onEscapeKeyDown={e=>{if(searching){e.preventDefault();closeSearch()}else if(p.locked){e.preventDefault();p.onUnlock()}}}>
 <header className="explore-header"><div><DialogTitle>Explore</DialogTitle><DialogDescription>{p.books.map(b=>NAMES[b]).join(' · ')}</DialogDescription></div><button className="icon-button explore-close" aria-label="Exit full screen" onClick={()=>p.onOpenChange(false)}><X size={22}/></button></header>
 <div className="explore-toolbar"><div className="explore-view-tools"><div className="explore-views" role="group" aria-label="Full screen visualization"><button aria-pressed={p.view==='columns'} onClick={()=>{p.onView('columns');if(searching)closeSearch()}}><Columns3 size={16}/>Columns</button><button aria-pressed={p.view==='circle'} onClick={()=>{p.onView('circle');if(searching)closeSearch()}}><Orbit size={16}/>Circle</button></div><button ref={searchButton} className="icon-button explore-search-trigger" aria-label={searching?'Close passage search':'Search passages'} aria-expanded={searching} aria-controls="explore-search" onClick={()=>searching?closeSearch():openSearch()}><Search size={19}/></button></div><button className="scrub-toggle" hidden={searching} onClick={()=>p.locked?p.onUnlock():p.onSelect(p.displayed)}>{p.locked?<Unlock size={16}/>:<LockKeyhole size={16}/>}{p.locked?'Resume':'Hold'}</button></div>
 {searching?<section id="explore-search" className="explore-search" aria-label="Passage search"><form className="explore-search-form" role="search" onSubmit={e=>{e.preventDefault();const target=firstSearchResult(p.searchResult);if(p.query.trim()&&target)choose(target)}}><button type="button" className="icon-button" aria-label="Back to visualization" onClick={closeSearch}><ArrowLeft size={20}/></button><div className="explore-search-input"><Search size={18}/><input ref={searchInput} type="search" aria-label="Find a passage, phrase, or reference" aria-controls="explore-search-results" aria-describedby="explore-search-help" enterKeyHint="search" autoComplete="off" spellCheck={false} value={p.query} placeholder="Reference or keyword…" onChange={e=>p.onQuery(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();dialog.current?.querySelector<HTMLButtonElement>('#explore-search-results .passage-result')?.focus()}}}/>{p.query&&<button type="button" className="icon-button" aria-label="Clear search" onClick={()=>{p.onQuery('');searchInput.current?.focus()}}><X size={17}/></button>}</div></form><p id="explore-search-help" className="explore-search-help">Try “Matthew 14” or {p.edition==='SBLGNT'?'“λόγος”':'“bread”'} · {p.edition==='SBLGNT'?'Greek':p.edition} · all four Gospels</p><PassageSearchResults id="explore-search-results" result={p.searchResult} selectedId={p.group.id} edition={p.edition} textReady={p.textReady} textError={p.textError} onRetry={p.onRetryText} onSelect={choose}/></section>:<>
 <p className="explore-instructions" id="explore-instructions">Drag to explore · lift to hold</p>
 <div className="explore-canvas" aria-describedby="explore-instructions"><PassageMap index={p.index} books={p.books} group={p.group} groups={p.groups} preview={p.preview} locked={p.locked} onSelect={p.onSelect} onPreview={p.onPreview} onRead={(b,c)=>p.onSelect(makeReading(b,c,undefined,p.index)!)} onUnlock={p.onUnlock} view={p.view} scale={p.scale} zoom={1} focus={false} immersive/></div>
 <footer className="explore-selection"><div className="explore-selection-heading"><span className="overline">{p.locked?'PASSAGE HELD':'EXPLORING'}</span><div className="explore-reading-actions"><button className="icon-button" aria-label="Previous source passage" onClick={()=>step(-1)}><ChevronLeft size={18}/></button><button className="icon-button" aria-label="Next source passage" onClick={()=>step(1)}><ChevronRight size={18}/></button><button className="read-selection" onClick={()=>{readOnClose.current=true;p.onRead()}}><BookOpen size={17}/>Read</button></div></div><h2>{p.displayed.title}</h2><p>{p.displayed.passages.filter(v=>p.books.includes(v.book)).sort((a,b)=>p.books.indexOf(a.book)-p.books.indexOf(b.book)).map(refLabel).join(' · ')}</p></footer>
 </>}
 </DialogContent></Dialog>;
}
