"use client";
import {useEffect,useState} from 'react';
import {Download,ArrowUpRight} from 'lucide-react';
import {NAMES,refLabel} from '@/lib/gospel';
import type {Index,Group} from '@/lib/gospel';
import type {LexicalStats,LexicalSide} from '@/lib/lexical-statistics';
import {createStatisticsLoader} from '@/lib/statistics-loader';
import {recoverStatistics} from '@/lib/recover-statistics';
// Analysis always measures the Greek text, independently of the reading edition.
const edition='SBLGNT';
const loader=createStatisticsLoader();
const pct=(n:number,total:number)=>total?(100*n/total).toFixed(1):'0.0';
export function LexicalAnalysis({index,books,onSelect}:{index:Index;books:string[];onSelect:(g:Group,pair:string)=>void}){
 const [stats,setStats]=useState<LexicalStats>(),[failure,setFailure]=useState(''),[calculated,setCalculated]=useState(false),[attempt,setAttempt]=useState(0),[pair,setPair]=useState(''),[sort,setSort]=useState('similarity'),[query,setQuery]=useState('');
 useEffect(()=>{let live=true;setFailure('');setStats(undefined);setCalculated(false);
 loader.load(index,edition,()=>recoverStatistics(index,edition)).then(result=>{if(live){setStats(result.stats);setCalculated(result.calculated)}}).catch(error=>{if(live)setFailure(error instanceof Error?error.message:'Please check your connection and retry.')});return()=>{live=false};},[index,attempt]);
 const pairs=stats?.pairs.filter(p=>books.includes(p.a)&&books.includes(p.b))||[];
 const selected=pairs.find(p=>p.a+'-'+p.b===pair)||pairs[0];
 const rows=selected?.rows.filter(r=>{const g=index.groups.find(g=>g.id===r.id)!;return [g.title,g.sourceRefs].join(' ').toLowerCase().includes(query.toLowerCase())}).slice().sort((a,b)=>sort==='unmatched'?(b.aWords+b.bWords-2*b.matched)-(a.aWords+a.bWords-2*a.matched):sort==='source'?index.groups.findIndex(g=>g.id===a.id)-index.groups.findIndex(g=>g.id===b.id):(b.score??-1)-(a.score??-1))||[];
 function download(){if(!stats)return;const csv=[['edition','revision','gospel_a','gospel_b','section','title','references_a','references_b','words_a','words_b','aligned_pairs','unmatched_a','unmatched_b','similarity_percent','status']];for(const p of pairs)for(const r of p.rows){const g=index.groups.find(g=>g.id===r.id)!;csv.push([edition,index.revision,NAMES[p.a],NAMES[p.b],g.section,g.title,refLabel(g.passages.find(v=>v.book===p.a)!),refLabel(g.passages.find(v=>v.book===p.b)!),String(r.aWords),String(r.bWords),r.limited?'':String(r.matched),r.limited?'':String(r.aWords-r.matched),r.limited?'':String(r.bWords-r.matched),r.score===null?'':(r.score*100).toFixed(3),r.limited?'not computed':'phrase-supported LCS'])}const u=URL.createObjectURL(new Blob([csv.map(r=>r.map(v=>'"'+v.replaceAll('"','""')+'"').join(',')).join('\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='gospel-atlas-wording-'+edition+'.csv';a.click();URL.revokeObjectURL(u)}
 function bar(book:string,s:LexicalSide){return <div className="lexical-book" key={book}><div><strong>{NAMES[book]}</strong><span>{s.matched.toLocaleString()} aligned / {s.total.toLocaleString()} Greek words · {pct(s.matched,s.total)}%</span></div><div className="lexical-bar" role="img" aria-label={`${NAMES[book]}: ${s.matched} aligned, ${s.unmatched} unmatched in compared sections, ${s.unexamined} not computed, ${s.outside} outside this pair’s source groups.`}>{[['matched',s.matched],['unmatched',s.unmatched],['unexamined',s.unexamined],['outside',s.outside]].map(([k,n])=><span key={k} className={'lex-'+k} style={{width:100*Number(n)/(s.total||1)+'%'}}/>)}</div></div>}
 return <section className="lexical-analysis"><div className="analysis-heading"><div><span className="overline">GREEK · {edition} · WHOLE-GOSPEL WORDING</span><h2>Shared Greek wording</h2><p>Aligned Greek word positions across the 184 source sections. Each position is counted once per Gospel and comparison partner.</p><p>Both statistics use SBLGNT Greek, regardless of your reading edition.</p></div><button className="secondary-button" disabled={!pairs.length} onClick={download}><Download size={16}/>Export Greek wording CSV</button></div>
 {failure?<div className="text-load-error" role="alert"><strong>Wording statistics could not load.</strong><p>{failure}</p><button className="text-button" onClick={()=>{setFailure('');setAttempt(n=>n+1)}}>Retry statistics</button></div>:!stats?<p className="loading" role="status">Loading wording statistics…</p>:pairs.length===0?<p className="notice">Select at least two Gospels to compare wording.</p>:<>{calculated&&<p className="statistics-recovery" role="status">Statistics recovered from the verified {edition} text and current passage index.</p>}<div className="lexical-legend"><span><i className="lex-matched"/>Aligned</span><span><i className="lex-unmatched"/>Unmatched within groups</span><span><i className="lex-outside"/>Outside this pair’s groups</span>{pairs.some(p=>p.left.unexamined||p.right.unexamined)&&<span><i className="lex-unexamined"/>Not computed</span>}</div><div className="lexical-pairs">{pairs.map(p=><button key={p.a+p.b} className={'lexical-card '+(selected===p?'active':'')} aria-pressed={selected===p} onClick={()=>{setPair(p.a+'-'+p.b);setQuery('')}}><div className="lexical-card-title"><strong>{NAMES[p.a]} ↔ {NAMES[p.b]}</strong><span>{p.rows.length} groups</span></div>{bar(p.a,p.left)}{bar(p.b,p.right)}<span className="lexical-card-action">Inspect Greek passages <ArrowUpRight size={14}/></span></button>)}</div>
 {selected&&<section className="lexical-inspect"><h3>{NAMES[selected.a]} & {NAMES[selected.b]} · inspect the Greek passages</h3><div className="lexical-filters"><input aria-label="Filter wording comparisons" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a passage in these results…"/><select aria-label="Sort wording comparisons" value={sort} onChange={e=>setSort(e.target.value)}><option value="similarity">Most similar wording</option><option value="unmatched">Most unmatched words</option><option value="source">Source section order</option></select></div><p className="method-caption">Greek similarity = 2 × aligned words ÷ combined Greek words. Unmatched counts: {NAMES[selected.a]} / {NAMES[selected.b]}. Select a row to open its normalized Greek comparison.</p><div className="lexical-rows">{rows.map(r=>{const g=index.groups.find(g=>g.id===r.id)!;return <button className="lexical-row" key={r.id} onClick={()=>onSelect(g,selected.a+'-'+selected.b)}><span><small>§{g.section}</small><strong>{g.title}</strong><span>{refLabel(g.passages.find(p=>p.book===selected.a)!)} · {refLabel(g.passages.find(p=>p.book===selected.b)!)}</span></span><span className="lexical-score">{r.score===null?'Not computed':(r.score*100).toFixed(1)+'%'}<small>{r.limited?'':`${r.aWords-r.matched} / ${r.bWords-r.matched} unmatched`}</small></span><ArrowUpRight size={15}/></button>})}{!rows.length&&<p className="notice">No passages match this filter.</p>}</div></section>}</>}
 <details className="lexical-method"><summary>Calculation, scope & interpretation</summary><p>Phrase-supported longest common subsequence within each source section: case, Greek accents, final sigma and apostrophe style are folded; punctuation is excluded. Both analysis sections use SBLGNT Greek word counts. Changing the reading edition does not change these statistics. Only consecutive runs of at least two words, including a word beyond common connectors, count as matches. Isolated words and connector-only fragments are excluded, using the same rule as the reader. Matching compares word forms, not dictionary lemmas or inferred meanings. A word position aligned in any included group counts as aligned once; unmatched means examined but never aligned. “Outside” means outside this pair’s source groups, not unique material.</p><p>Only the 184 main source sections enter this baseline. Smaller source units, editorial selections and related-episode studies are excluded. Disputed source groupings remain included; see each passage’s Sources & context. Sections over the interactive alignment limit are explicitly marked “Not computed”. Unmatched words are not automatically additional details, authorial insertions, deletions, or evidence about event identity. CSV rows describe individual sections; do not sum overlapping section rows to reproduce the union totals.</p></details>
 </section>;
}
