import {ArrowUpRight} from 'lucide-react';
import {isRelatedTeaching} from '@/lib/gospel';
import type {Group,Index} from '@/lib/gospel';

export function Subsections({group,index,onSelect}:{group:Group;index:Index;onSelect:(g:Group)=>void}){const parent=index.groups.find(g=>g.id===(group.parentId||group.id));const children=index.groups.filter(g=>g.parentId===parent?.id);if(!parent||!children.length)return null;return <div className="subsection-nav"><span className="overline">WITHIN §{parent.section}</span><select aria-label="Source subsection" value={group.id} onChange={e=>onSelect(index.groups.find(g=>g.id===e.target.value)!)}><option value={parent.id}>Whole section · {parent.title}</option>{children.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select>{group.parentId&&<button className="text-button" onClick={()=>onSelect(parent)}>Whole section</button>}</div>}

export function Evidence({group,index}:{group:Group;index:Index}){return <div className="evidence"><span className="overline">RELATIONSHIP EVIDENCE</span><h3>{(group.kind==='focused'||group.kind==='editorial-unit')?'An editorial close comparison':isRelatedTeaching(group)?'A shared teaching across settings':group.kind==='related'?'Related accounts':group.kind==='disputed'?'An identification with differing interpretations':group.kind==='reading'?'Direct reading':'A source-attributed grouping'}</h3><p>{group.status}.</p>{group.sourceUrl&&<><a href={group.sourceUrl} target="_blank" rel="noreferrer" className="source-link">{group.sourceLabel||`A. T. Robertson · Harmony (1922), §${group.section}`}<ArrowUpRight size={15}/></a><p className="source-reference">{group.sourceRefs}</p></>}{group.kind!=='reading'&&<p>A grouping supports comparison. It does not by itself establish word-for-word equivalence or settle every question about event identity.</p>}{group.notes.map((n,i)=><section className="interpretation-note" key={i}><h4>{n.label}</h4><p>{n.text}</p><a target="_blank" rel="noreferrer" href={n.url}>{n.source}<ArrowUpRight size={14}/></a></section>)}<details><summary>About this mapping</summary><p>The main overview transcribes {index.sourceSections} Gospel-bearing sections from Robertson’s analytical outline. Its headings and groupings are interpretive. All {index.referenceAudit.checked} main reference sets were compared with the source’s separate passage register: {index.referenceAudit.agree} agree, with one documented boundary difference in §54. This checks transcription, not event identity. The {index.sourceSubsections} detailed source units are transcribed from explicit outline rows. Another {index.editorialUnits} close reading selections use editorial boundaries within those source groups. Interpretive review continues.</p><p>Traditional, creedal Christian study guides the project. Attributed interpretations remain distinct from the biblical text and calculated comparisons.</p></details></div>}


